### ISSUE TITLE
Perbaikan dokumentasi sso-php

### ISSUE THREAD

**Issue by gairawan** [ristekusdi/ristekusdi.github.io#6]
Perbaikan dokumentasi pada https://ristekusdi.github.io/sso-php.html#daftar-perintah-auth
pada bagian Auth CodeIgniter 3.x ubah kata-kata berikut.
Dari : 
// Mengecek apakah ada pengguna yang login atau tidak.
$this->webguard->check();

Menjadi : 
// Mengecek apakah ada pengguna telah login dengan cara yang benar (via sso) atau tidak
$this->webguard->check();

**Comment by kresnasatya** [comment]
Gimana kalo begini seperti di bawah?

```diff
- // Mengecek apakah ada pengguna telah login dengan cara yang benar (via sso) atau tidak
+ // Mengecek apakah ada pengguna telah login via SSO atau tidak
```

**Comment by gairawan** [comment]
Ya bisa begitu, dan sepertinya itu lebih baik.
